package com.opsmind.audit;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    SERVICE_CREATED,
    SERVICE_UPDATED,
    SERVICE_DELETED,
    DEPLOYMENT_STARTED,
    DEPLOYMENT_COMPLETED,
    DEPLOYMENT_FAILED,
    INCIDENT_CREATED,
    INCIDENT_UPDATED,
    AI_ANALYSIS_REQUESTED,
    ROLLBACK_REQUESTED,
    ROLLBACK_COMPLETED
}
